# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20161101_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagenportada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
