# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20161103_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
    ]
